let currentLang = 'ru';

const strings = {
  ru: {
    gameTitle: 'Охота на брейнрота',
    play: 'Играть',
    collection: 'Коллекция',
    settings: 'Настройки',
    upgrades: 'Улучшения',
    howToPlay: 'Как играть',
    pasta: 'Паста',
    incomePerSec: 'Доход/сек',
    buyFor: 'за',
    lvl: 'Ур.',
    selectMemes: 'Выбор',
    selectMeme: 'Выбор мема',
    menu: 'В меню',
    back: 'Назад',
    boss: 'Боссы',
    bossInfo: 'Боссы',
    bossTitle: 'Боссы',
    claimBoss: 'Призвать босса!',
    bossAwake: 'Босс пробудился!',
    bossIncome: '×10 дохода',
    bossPuzzleComplete: '💎 ×10 дохода на доске',
    noMemeFound: 'Пока ничего не открыто. Купите или объедините мемов!',
    themeLight: 'Светлая тема',
    themeDark: 'Тёмная тема',
    volumeLabel: 'Громкость музыки',
    muteOn: 'Отключить звук',
    muteOff: 'Включить звук',
    finish: 'Максимум',
    upgradeBuy: 'Улучшить за',
    currentOffline: 'Текущий',
    currentBoost: 'Текущая',
    nextOffline: 'Следующий',
    nextBoost: 'Следующая',
    offlineHeader: 'Офлайн-доход',
    boostHeader: 'Длительность буста',
    levelX: 'Уровень',
    sec: 'сек',
    returnMenu: 'Вернуться в меню',
    dailyBonus: 'Ежедневный бонус',
    dailyDayOf: 'День',
    dailyClaim: 'Забрать',
    invasionTimer: 'Вторжение через',
    invasionNow: 'сейчас',
    invasionBlocked: 'Мем-вторжение отражено',
    invasionNoSpace: 'нет свободного места',
    invasionTitle: 'Мем-вторжение!',
    hhActive: 'Счастливый час активен! ×3 доход',
    hhPending: 'Счастливый час через',
    hhDone: 'Счастливый час завершён — приходите завтра',
    hhDoneShort: 'завершён',
    fragmentFound: '💎 Найден новый фрагмент босса!',
    newCharacter: 'Разблокирован новый персонаж',
    offlineToast: 'пасты',
    offlineAway: 'за',
    offlineAbsence: 'отсутствия',
    purchase: 'Купить за',
    guideTitle: 'Как играть',
    guideMergeTitle: 'Слияние мемов',
    guideMergeText: 'Тапните по мему — он выделится жёлтой обводкой. Тапните по другому мему того же уровня — они сольются в мем уровнем выше. При слиянии вы получаете пасту.',
    guideBuyTitle: 'Покупка мемов',
    guideBuyText: 'Кнопка «Ур.N за M» покупает мем выбранного уровня. Выбрать уровень можно через раздел «Выбор». Цена растёт с каждой покупкой. Прямая покупка высокого уровня экономит время, но осколки босса не выпадают.',
    guideIncomeTitle: 'Доход',
    guideIncomeText: 'Каждый мем на доске приносит пасту в секунду. Доход растёт экспоненциально с уровнем. Чем выше уровень мема — тем больше пасты.',
    guideBoostTitle: 'Буст ×2',
    guideBoostText: 'Кнопка «×2» удваивает доход на 30 секунд. Кулдаун — 5 минут. Длительность можно увеличить в разделе Улучшения.',
    guideOfflineTitle: 'Офлайн-доход',
    guideOfflineText: 'При возвращении в игру начисляется паста за время отсутствия (до 4 часов, 10% от дохода). Процент прокачивается в Улучшениях.',
    guideDailyTitle: 'Ежедневный бонус',
    guideDailyText: 'Заходите в игру 7 дней подряд — награда растёт с каждым днём. Пропуск дня сбрасывает серию до дня 1.',
    guideInvasionTitle: 'Мем-вторжение',
    guideInvasionText: 'Каждые 2 часа случайная пустая клетка заполняется бесплатным мемом уровня 3-5. Если нет места — вторжение отражается.',
    guideHHTitle: 'Счастливый час',
    guideHHText: 'Раз в день случайное 15-минутное окно между 10:00 и 22:00 — доход ×3. Совмещается с бустом ×2 (итого ×6). Таймер на главном экране.',
    guideBossTitle: 'Боссы',
    guideBossText: 'Слияния уровня 4+ с шансом 2% дают осколки босса (до 3 в день). Соберите 9 осколков — босс появится на доске с доходом ×10. Новый босс каждую неделю.',
    guideUpgradeTitle: 'Улучшения',
    guideUpgradeText: 'В разделе Улучшения можно прокачать офлайн-доход (до 30%) и длительность буста (до 60 секунд) за пасту.',
    guideReturn: 'Вернуться в меню',
    buyFirstMeme: 'Купите первого мема!',
    progressArrow: '→',
    progressLabel: 'Ур.',
    invasionInfoTitle: 'Мем-вторжение',
    invasionInfoText: 'Раз в 2 часа случайная пустая клетка заполняется бесплатным мемом уровня 3-5. Если нет места — вторжение отражается.',
    hhInfoTitle: 'Счастливый час',
    hhInfoText: 'Раз в день в случайное время между 10:00 и 22:00 — доход ×3 на 15 минут. Совмещается с бустом ×2.',
    bossModalTitle: 'Боссы',
    bossModalInfo: 'При слиянии мемов уровня 4 и выше с шансом 2% выпадает осколок босса (до 3 в день). Соберите 9 осколков (пазл 3×3) — и босс появится в случайной клетке на доске. Уровень босса = ваш максимальный уровень на доске, доход ×10.\n\nБосс исчезает в конце недели. Осколки обнуляются каждый понедельник. Разные боссы — каждую неделю.',
    langLabel: 'Язык / Language',
    langRu: 'Русский',
    langEn: 'English',
  },
  en: {
    gameTitle: 'Brainrot Hunt',
    play: 'Play',
    collection: 'Collection',
    settings: 'Settings',
    upgrades: 'Upgrades',
    howToPlay: 'How to Play',
    pasta: 'Pasta',
    incomePerSec: 'Income/s',
    buyFor: 'for',
    lvl: 'Lv.',
    selectMemes: 'Select',
    selectMeme: 'Select Meme',
    menu: 'Menu',
    back: 'Back',
    boss: 'Bosses',
    bossInfo: 'Bosses',
    bossTitle: 'Bosses',
    claimBoss: 'Summon Boss!',
    bossAwake: 'Boss awakened!',
    bossIncome: '×10 income',
    bossPuzzleComplete: '💎 ×10 income on board',
    noMemeFound: 'Nothing unlocked yet. Buy or merge memes!',
    themeLight: 'Light Theme',
    themeDark: 'Dark Theme',
    volumeLabel: 'Music Volume',
    muteOn: 'Mute Sound',
    muteOff: 'Unmute Sound',
    finish: 'Max',
    upgradeBuy: 'Upgrade for',
    currentOffline: 'Current',
    currentBoost: 'Current',
    nextOffline: 'Next',
    nextBoost: 'Next',
    offlineHeader: 'Offline Income',
    boostHeader: 'Boost Duration',
    levelX: 'Level',
    sec: 's',
    returnMenu: 'Back to Menu',
    dailyBonus: 'Daily Bonus',
    dailyDayOf: 'Day',
    dailyClaim: 'Claim',
    invasionTimer: 'Invasion in',
    invasionNow: 'now',
    invasionBlocked: 'Invasion repelled',
    invasionNoSpace: 'no free space',
    invasionTitle: 'Meme Invasion!',
    hhActive: 'Happy Hour active! ×3 income',
    hhPending: 'Happy Hour in',
    hhDone: 'Happy Hour finished — come back tomorrow',
    hhDoneShort: 'finished',
    fragmentFound: '💎 Boss fragment found!',
    newCharacter: 'New character unlocked',
    offlineToast: 'pasta',
    offlineAway: 'in',
    offlineAbsence: 'away',
    purchase: 'Buy for',
    guideTitle: 'How to Play',
    guideMergeTitle: 'Meme Merging',
    guideMergeText: 'Tap a meme — it gets a yellow outline. Tap another meme of the same level — they merge into a higher level meme. You get pasta for merging.',
    guideBuyTitle: 'Buying Memes',
    guideBuyText: 'The "Lv.N for M" button buys a meme of the selected level. Choose the level from the "Select" panel. Price increases with each purchase. Buying high levels saves time, but boss fragments won\'t drop.',
    guideIncomeTitle: 'Income',
    guideIncomeText: 'Every meme on the board generates pasta per second. Income grows exponentially with level. Higher level = more pasta.',
    guideBoostTitle: 'Boost ×2',
    guideBoostText: 'The "×2" button doubles income for 30 seconds. Cooldown: 5 minutes. Duration can be upgraded in Upgrades.',
    guideOfflineTitle: 'Offline Income',
    guideOfflineText: 'When you return to the game, you earn pasta for time away (up to 4 hours, 10% of income). Percentage can be upgraded.',
    guideDailyTitle: 'Daily Bonus',
    guideDailyText: 'Log in 7 days in a row — rewards grow each day. Missing a day resets the streak to day 1.',
    guideInvasionTitle: 'Meme Invasion',
    guideInvasionText: 'Every 2 hours a random empty cell gets a free level 3-5 meme. If the board is full, the invasion is repelled.',
    guideHHTitle: 'Happy Hour',
    guideHHText: 'Once a day, a random 15-minute window between 10:00 and 22:00 — ×3 income. Stacks with ×2 boost (total ×6). Timer on the main screen.',
    guideBossTitle: 'Bosses',
    guideBossText: 'Level 4+ merges have a 2% chance to drop boss fragments (max 3 per day). Collect 9 fragments — the boss appears on the board with ×10 income. New boss every week.',
    guideUpgradeTitle: 'Upgrades',
    guideUpgradeText: 'In the Upgrades section, you can improve offline income (up to 30%) and boost duration (up to 60 seconds) using pasta.',
    guideReturn: 'Back to Menu',
    buyFirstMeme: 'Buy your first meme!',
    progressArrow: '→',
    progressLabel: 'Lv.',
    invasionInfoTitle: 'Meme Invasion',
    invasionInfoText: 'Every 2 hours a random empty cell gets a free level 3-5 meme. If the board is full, the invasion is repelled.',
    hhInfoTitle: 'Happy Hour',
    hhInfoText: 'Once a day at a random time between 10:00-22:00 — ×3 income for 15 minutes. Stacks with boost.',
    bossModalTitle: 'Bosses',
    bossModalInfo: 'Level 4+ merges have a 2% chance to drop a boss fragment (max 3 per day). Collect 9 fragments (3×3 puzzle) and the boss appears in a random cell on the board. Boss level = your max board level, income ×10.\n\nThe boss disappears at the end of the week. Fragments reset every Monday. Different bosses each week.',
    langLabel: 'Language / Язык',
    langRu: 'Русский',
    langEn: 'English',
  }
};

const memeDescriptionsEn = {
  1: "Ballerina Cappuccina\nA ballerina with a coffee cup for a head. Wife of Cappuccino Assassino, but their relationship ended in a dramatic divorce after a scandalous affair. She is usually seen dancing or singing.",
  2: "Bobrito Bandito\nAn anthropomorphic beaver dressed as a gangster. Wears a trench coat, suit with tie, and a fedora. Often seen with a Tommy gun and smoking.",
  3: "Bombardiro Crocodilo\nA WWII bomber with a crocodile head flying in the sky, with a nuclear bomb below.",
  4: "Bombombini Gusini\nBombardiro Crocodilo's brother. A goose-bomber hybrid carrying grenades. Died at the end of the Second Croco-Avian War.",
  5: "Brr Brr Patapim\nA hybrid of a giant proboscis monkey and a tree. Hates Slim the blue frog. Found a golden hat in the forest.",
  6: "Cappuccino Assassino\nA coffee cup with eyes, arms and legs, armed with katanas. Wears a Naruto headband. A stealthy assassin who strikes at night.",
  7: "La Vaca Saturno Saturnita\nSaturn with a cow's head and human legs. The most powerful character, possessing universe-scale abilities like a black hole.",
  8: "Lirili Larila\nA two-legged elephant covered in cacti and wearing sandals. Can control time and predict the future. Guardian of the desert.",
  9: "Tralalero Tralala\nA three-legged shark in blue Nike sneakers.",
  10: "Trippi Troppi\nA fish with a fat man's body and bear arms. An aquatic ruler who eats everything. Also depicted as a shrimp with a cat head.",
  11: "Trulimero Trulicina\nA fish with a cat's head and four human legs.",
  12: "Tung Tung Tung Sahur\nA log with a baseball bat, the main villain. One of the strongest AI-creatures. Hunts anyone who says his name three times.",
  13: "Chimpanzini Bananini\nA chimpanzee with green fur inside a banana.",
  14: "Spioniro Golubiro\nAn experienced private detective pigeon with a sharp eye and even sharper beak. Specializes in surveillance and urban mysteries.",
  15: "Blueberrinni Octopussini\nAn octopus with a hairy blueberry for a head, living on the ocean floor among coral reefs.",
  16: "Boneca Ambalabu\nA frog with a car tire for a body and human legs. An evil entity terrorizing society. Very fast and dangerous.",
  17: "Brri Brri Bicus Dicus Bombicus\nA bird with a raspberry necklace, golden gladiator armor, and a cape in front of the Colosseum.",
  18: "Brr Es Teh Patipum\nA creature resembling a glass of iced tea with human limbs and a face.",
  19: "Burbaloni Luliloli\nA divine capybara inside a coconut on the shores of Bali. Worshiped as a coconut god.",
  20: "Garamaraman dan Madudungdung\nA salt shaker and a honey pot with faces and human legs.",
  21: "Glorbo Fruttodrillo\nA watermelon crocodile living deep in the swamps. Can shoot exploding watermelon seeds.",
  22: "Cocofanto Elefanto\nA baby elephant-coconut hybrid, smiling in the jungle.",
  23: "Crocodildo Penisini\nA crocodile with a pineapple body wearing sunglasses on the beach.",
  24: "Frigo Camelo\nA camel with a refrigerator body and large boots on its feet.",
  25: "Frulli Frulla\nA penguin with a toucan's beak living in the desert, who loves coffee. Lirili Larila's best friend.",
  26: "Espressona Signora\nA woman with an espresso cup for a head, dressed in black and smoking a cigarette. Ballerina Cappuccina's rival.",
  27: "Aduh 9 April Udah Dekat\nA monster embodiment of the number 9, terrorizing school children.",
  28: "Aaaaaaaro Hamstero\nA lemon-hamster hybrid screaming on a yellow background.",
  29: "Abonono Schimpazinono\nA green chimpanzee with half an avocado for a body, with a UFO in the background.",
  30: "Avocadini Antilopini\nAn antelope-avocado hybrid.",
  31: "Avocadini Guffo\nA green owl with an avocado body. A fat wise owl, very useful.",
  32: "Australini Barbacuenini\nA brain with foliage on a plate of spaghetti and tomatoes.",
  33: "Akulini Cactusini\nA blue shark with a cactus body, swinging a baseball bat. Wears Nike sneakers.",
  34: "Alessio\nA soccer ball in brown boots on giraffe legs, wearing a red cap.",
  35: "Almohada del Ramon\nA pillow belonging to Ramon. Very angry about being crushed all day.",
  36: "Ananasita Owlita\nAn adorable owl walking through the forest at night among fireflies. Has a pineapple body.",
  37: "Ananasopotam\nA pineapple hippopotamus living in a swamp.",
  38: "Ananitto Giraffini\nA giraffe with a pineapple body, walking through the savanna.",
  39: "Anpali Babbel\nA Tetris figure with a human face, arms and legs, holding a mobile phone.",
  40: "Antonio\nA man with a broccoli head, wearing glasses and a green suit with a tie.",
  41: "Apponini Catonlini\nA cat-apple hybrid living in Mexico, singing folk melodies.",
  42: "Arachinnu Watermellichinnu\nA green spider with a watermelon body and ten legs.",
  43: "Armodillo Cocodillo\nAn armadillo living inside a coconut on a desert beach.",
  44: "Armodillo Fartillo\nAn armadillo from the 'Ask Orange' episode on the Annoying Orange YouTube channel.",
  45: "Aeroplanino Gattino\nA Boeing 737 airplane with a cat's head. Can do aerial loops while sipping cappuccino.",
  46: "Baaantiiireee\nA tire sitting on a horse, holding two flaming knives in the middle of a night field.",
  47: "Ballerino Lololo\nA milkshake with very muscular human arms and legs, a ballet dancer.",
  48: "Bambini Crostini\nA deer with a body resembling a crunchy croissant.",
  49: "Bambini Tankini Banana Yeldini Pierdolini\nA small tank with a sausage cannon, operated by a banana.",
  50: "Bambini Felicini\nA hybrid creature with the upper body of a cheerful white beluga whale and the lower body of a human baby.",
};

const bossDescriptionsEn = {
  1: "Tung Tung Tung Assasino Boneka\nA fusion of three characters: Tung-Tung-Tung Sahur, Cappuccino Assassino, and Boneca Ambalabu.",
  2: "Kudanile Astronote\nA hippo-astronaut with a watermelon body.",
  3: "Penguinator Termoregulator\nA penguin air conditioner.",
};

function t(key) {
  const s = strings[currentLang];
  if (!s) return key;
  return s[key] || key;
}

function getMemeDescriptionEn(id) {
  return memeDescriptionsEn[id] || '';
}

function getBossDescriptionEn(week) {
  return bossDescriptionsEn[week] || '';
}

function getLang() {
  return currentLang;
}

function setLang(lang) {
  currentLang = lang;
}

function initLang() {
  if (typeof navigator !== 'undefined' && navigator.language) {
    if (navigator.language.startsWith('ru')) currentLang = 'ru';
  }
}

export { t, getLang, setLang, initLang, getMemeDescriptionEn, getBossDescriptionEn };
